

server:
  port: 9002
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/wx_dc
    name: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: none
security:
  basic:
    enabled: false
